---
title: MACC NYC
timezone: UTC
collections:
  documents:
    title: Documents
    output: true
    permalink: "/:collection/:name"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
plugins:
  - jekyll-multiple-languages-plugin
languages: ["en", "es"]
exclude_from_localizations: ["js", "img", "css", "fonts"]
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: The Metropolitan Anarchist Coordinating Council
url: https://maccnyc.github.io/
baseurl: ''
wikiurl: https://wiki.macc.nyc
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
lsi: false
safe: true
future: false
source: "."
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  auto_ids: true
  toc_levels: 1..2
